### PR TITLE
Random fact generator js

### PR DESCRIPTION
**Pull request by rbaia28**
Added javascript page to generate random facts
created HTML page for the js page to populate on

planning on converting to PHP as a HTML page cant live on a PHP centric site. Created just to test and play with js math. function. 

If i wanted to keep this JS page as JS, would i start looking into AJAX?

### CODE REVIEW

**Review by billythakidd04 — CHANGES_REQUESTED** [review]
Two things:
1. conflicts
2. javascript.js is possibly the worst name ever... lol

**Comment by billythakidd04** [comment]
@rbaia28 there's no reason to use ajax at all unless you want to store data on the server. So if you loaded those "quotes" into a db, that would be one thing. But as it sits, there's no reason for an ajax call at all.

**Review by rbaia28 — COMMENTED** [review]
Changes have been made, file name updated and removed duplicate code

**Review by billythakidd04 — CHANGES_REQUESTED** [review]
now you have javascript.js and randomfact.js which are both the same file...

**Review by billythakidd04 — APPROVED** [review]

**Pull request merged**
